In [6]:
import pandas as pd
import numpy as np

In [2]:
!ls

FoodRatings_all_same_5.csv            MyFoodRatings_PracticeQuestions.ipynb
FoodRatings_all_same_5_4_3.csv        PCA+and+Dimensionality+Reduction.pdf
Introduction+to+Matrices+(2).pdf      Principal Component Analysis.docx
MyFoodRatings.csv                     ~$incipal Component Analysis.docx


In [3]:
rating = pd.read_csv("MyFoodRatings.csv")

In [9]:
rating.head(12)

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        4       4       4         0            0     0      0      0   
2     C        3       3       3         0            0     0      0      0   
3     D        2       2       2         0            0     0      0      0   
4     E        0       0       0         2            2     2      0      0   
5     F        0       0       0         1            1     1      0      0   
6     G        0       0       0         5            3     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      2      2   
9     J        0       0       0         0            0     0      1      1   
10    K        0       0       0         0            0     0      3      4   
11    L        0       0       0         0            0     0      2      2   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         4  
9         1  
10        4  
11        2

In [5]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 10 columns):
Name           12 non-null object
Chicken        12 non-null int64
Mutton         12 non-null int64
Paneer         12 non-null int64
ChowMein       12 non-null int64
SpringRolls    12 non-null int64
Momo           12 non-null int64
Sushi          12 non-null int64
Ramen          12 non-null int64
Tempura        12 non-null int64
dtypes: int64(9), object(1)
memory usage: 1.0+ KB


In [11]:
rating.columns

Index(['Name', 'Chicken', 'Mutton', 'Paneer', 'ChowMein', 'SpringRolls',
       'Momo', 'Sushi', 'Ramen', 'Tempura'],
      dtype='object')

In [22]:
U, s, VT = np.linalg.svd(rating.iloc[:, 1:], full_matrices=True)

In [27]:
U.shape, VT.shape

((12, 12), (9, 9))

In [28]:
s

array([1.27279221e+01, 1.05770379e+01, 8.84826058e+00, 1.24205263e+00,
       1.06125858e+00, 4.06927550e-01, 4.88571062e-16, 3.23597471e-16,
       2.65957113e-32])

In [29]:
np.diag(s[:3])

array([[12.72792206,  0.        ,  0.        ],
       [ 0.        , 10.57703788,  0.        ],
       [ 0.        ,  0.        ,  8.84826058]])

In [40]:
U[:,:3]

array([[-6.80413817e-01,  0.00000000e+00,  1.50959901e-33],
       [-5.44331054e-01,  0.00000000e+00, -1.18467457e-17],
       [-4.08248290e-01,  0.00000000e+00, -9.47718760e-34],
       [-2.72165527e-01,  0.00000000e+00,  2.36934913e-17],
       [ 0.00000000e+00, -3.26217015e-01, -7.70125425e-17],
       [ 0.00000000e+00, -1.63108508e-01,  7.26603708e-17],
       [ 0.00000000e+00, -6.64310100e-01,  7.72458645e-33],
       [ 0.00000000e+00, -6.52434031e-01,  2.03411785e-17],
       [ 0.00000000e+00,  0.00000000e+00, -5.41047938e-01],
       [ 0.00000000e+00,  0.00000000e+00, -1.93680321e-01],
       [ 0.00000000e+00,  0.00000000e+00, -7.20906926e-01],
       [ 0.00000000e+00,  0.00000000e+00, -3.87360641e-01]])

In [41]:
VT_df = pd.DataFrame(VT)

In [42]:
VT_df.iloc[:3]

0        1        2         3         4         5         6  \
0 -0.57735 -0.57735 -0.57735 -0.000000 -0.000000 -0.000000 -0.000000   
1  0.00000  0.00000  0.00000 -0.637875 -0.512261 -0.575068  0.000000   
2  0.00000  0.00000  0.00000  0.000000  0.000000  0.000000 -0.476163   

          7         8  
0 -0.000000 -0.000000  
1  0.000000  0.000000  
2 -0.557638 -0.679933

In [43]:
df_1 = pd.read_csv("FoodRatings_all_same_5.csv")

In [44]:
df_1

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         5            5     5      0      0   
5     F        0       0       0         5            5     5      0      0   
6     G        0       0       0         5            5     5      0      0   
7     H        0       0       0         5            5     5      0      0   
8     I        0       0       0         0            0     0      5      5   
9     J        0       0       0         0            0     0      5      5   
10    K        0       0       0         0            0     0      5      5   
11    L        0       0       0         0            0     0      5      5   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         5  
9         5  
10        5  
11        5

In [45]:
U,s,VT = np.linalg.svd(df_1.iloc[:,1:],full_matrices=True)

In [50]:
np.diag(s[:8])

array([[1.73205081e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.73205081e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.73205081e+01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.92523115e-16,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.79802815e-49, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.

In [53]:
df_2 = pd.read_csv('FoodRatings_all_same_5_4_3.csv')

In [54]:
df_2

Name  Chicken  Mutton  Paneer  ChowMein  SpringRolls  Momo  Sushi  Ramen  \
0     A        5       5       5         0            0     0      0      0   
1     B        5       5       5         0            0     0      0      0   
2     C        5       5       5         0            0     0      0      0   
3     D        5       5       5         0            0     0      0      0   
4     E        0       0       0         4            4     4      0      0   
5     F        0       0       0         4            4     4      0      0   
6     G        0       0       0         4            4     4      0      0   
7     H        0       0       0         4            4     4      0      0   
8     I        0       0       0         0            0     0      3      3   
9     J        0       0       0         0            0     0      3      3   
10    K        0       0       0         0            0     0      3      3   
11    L        0       0       0         0            0     0      3      3   

    Tempura  
0         0  
1         0  
2         0  
3         0  
4         0  
5         0  
6         0  
7         0  
8         3  
9         3  
10        3  
11        3

In [55]:
U,s,VT = np.linalg.svd(df_2.iloc[:,1:],full_matrices=True)

In [56]:
np.diag(s[:5])

array([[1.73205081e+01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.38564065e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.03923048e+01, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.92523115e-16,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        2.79802815e-49]])